### ISSUE TITLE
Cannot read property 'selections' of null

### ISSUE THREAD

**Issue by GuillaumeLeclerc** [monteirocode/graphql-mongodb-projection#1]
In some cases I get an error when generating a projection.

An example of failing info is available here: http://pastebin.com/1U1sMzvd

Here is the interesting part of the stack trace:

```
TypeError: Cannot read property 'selections' of null
    at infoToProjection (...graphql-mongodb-projection/dist/index.js:13:30)
    at context.selectionSet.selections.reduce (/...graphql-mongodb-projection/dist/index.js:18:43)
    at Array.reduce (native)
    at infoToProjection (...s/graphql-mongodb-projection/dist/index.js:13:42)
```

**Comment by monteirocode** [comment]
thanks for reporting I'll have a look at it now :)

**Comment by GuillaumeLeclerc** [comment]
I made a pull request fixing this. The bug was when you ask the relay cursor before the node
